package com.poli.health.aquamate.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val AquaMateLightColorScheme = lightColorScheme(
    primary = LightPrimary,
    onPrimary = LightOnPrimary,
    primaryContainer = LightPrimaryLight,
    onPrimaryContainer = LightOnPrimary,
    secondary = LightSecondary,
    onSecondary = LightOnSecondary,
    secondaryContainer = LightSecondary.copy(alpha = 0.12f),
    onSecondaryContainer = LightOnBackground,
    tertiary = LightPrimaryVariant,
    onTertiary = LightOnPrimary,
    tertiaryContainer = LightPrimaryVariant.copy(alpha = 0.12f),
    onTertiaryContainer = LightOnBackground,
    error = LightError,
    onError = LightOnPrimary,
    errorContainer = LightErrorLight,
    onErrorContainer = LightOnBackground,
    background = LightBackground,
    onBackground = LightOnBackground,
    surface = LightSurface,
    onSurface = LightOnSurface,
    surfaceVariant = LightSurfaceVariant,
    onSurfaceVariant = LightOnBackgroundSecondary,
    outline = LightDivider,
    outlineVariant = LightDivider.copy(alpha = 0.5f),
    surfaceTint = LightPrimary,
    inverseSurface = DarkSurface,
    inverseOnSurface = DarkOnSurface,
    inversePrimary = DarkPrimary,
    scrim = LightOnBackground.copy(alpha = OverlayOpacity.SCRIM_LIGHT)
)

val AquaMateDarkColorScheme = darkColorScheme(
    primary = DarkPrimary,
    onPrimary = DarkOnPrimary,
    primaryContainer = DarkPrimaryDark,
    onPrimaryContainer = DarkOnSurface,
    secondary = DarkSecondary,
    onSecondary = DarkOnSecondary,
    secondaryContainer = DarkSecondaryVariant.copy(alpha = 0.24f),
    onSecondaryContainer = DarkOnSurface,
    tertiary = DarkPrimaryVariant,
    onTertiary = DarkOnPrimary,
    tertiaryContainer = DarkPrimaryVariant.copy(alpha = 0.24f),
    onTertiaryContainer = DarkOnSurface,
    error = DarkError,
    onError = DarkOnPrimary,
    errorContainer = DarkErrorDark,
    onErrorContainer = DarkOnSurface,
    background = DarkBackground,
    onBackground = DarkOnBackground,
    surface = DarkSurface,
    onSurface = DarkOnSurface,
    surfaceVariant = DarkSurfaceVariant,
    onSurfaceVariant = DarkOnBackgroundSecondary,
    outline = DarkDivider,
    outlineVariant = DarkDivider.copy(alpha = 0.5f),
    surfaceTint = DarkPrimary,
    inverseSurface = LightSurface,
    inverseOnSurface = LightOnSurface,
    inversePrimary = LightPrimary,
    scrim = DarkOnBackground.copy(alpha = OverlayOpacity.SCRIM_DARK)
)

data class AquaMateExtendedColors(
    val success: androidx.compose.ui.graphics.Color,
    val onSuccess: androidx.compose.ui.graphics.Color,
    val successContainer: androidx.compose.ui.graphics.Color,
    val onSuccessContainer: androidx.compose.ui.graphics.Color,
    val warning: androidx.compose.ui.graphics.Color,
    val onWarning: androidx.compose.ui.graphics.Color,
    val warningContainer: androidx.compose.ui.graphics.Color,
    val onWarningContainer: androidx.compose.ui.graphics.Color,
    val info: androidx.compose.ui.graphics.Color,
    val onInfo: androidx.compose.ui.graphics.Color,
    val infoContainer: androidx.compose.ui.graphics.Color,
    val onInfoContainer: androidx.compose.ui.graphics.Color,
    val surfaceElevated1: androidx.compose.ui.graphics.Color,
    val surfaceElevated2: androidx.compose.ui.graphics.Color,
    val progressBackground: androidx.compose.ui.graphics.Color,
    val quickButtonPressed: androidx.compose.ui.graphics.Color,
    val waterGradientStart: androidx.compose.ui.graphics.Color,
    val waterGradientEnd: androidx.compose.ui.graphics.Color,
    val successGradientStart: androidx.compose.ui.graphics.Color,
    val successGradientEnd: androidx.compose.ui.graphics.Color
)

val AquaMateLightExtendedColors = AquaMateExtendedColors(
    success = LightSuccess,
    onSuccess = LightOnPrimary,
    successContainer = LightSuccessLight,
    onSuccessContainer = LightOnBackground,
    warning = LightWarning,
    onWarning = LightOnPrimary,
    warningContainer = LightWarningLight,
    onWarningContainer = LightOnBackground,
    info = LightInfo,
    onInfo = LightOnPrimary,
    infoContainer = LightInfo.copy(alpha = 0.12f),
    onInfoContainer = LightOnBackground,
    surfaceElevated1 = LightSurface,
    surfaceElevated2 = LightSurface,
    progressBackground = LightProgressBackground,
    quickButtonPressed = LightQuickButtonPressed,
    waterGradientStart = LightWaterGradientStart,
    waterGradientEnd = LightWaterGradientEnd,
    successGradientStart = LightSuccessGradientStart,
    successGradientEnd = LightSuccessGradientEnd
)

val AquaMateDarkExtendedColors = AquaMateExtendedColors(
    success = DarkSuccess,
    onSuccess = DarkOnPrimary,
    successContainer = DarkSuccessDark,
    onSuccessContainer = DarkOnSurface,
    warning = DarkWarning,
    onWarning = DarkOnPrimary,
    warningContainer = DarkWarningDark,
    onWarningContainer = DarkOnSurface,
    info = DarkInfo,
    onInfo = DarkOnPrimary,
    infoContainer = DarkInfo.copy(alpha = 0.24f),
    onInfoContainer = DarkOnSurface,
    surfaceElevated1 = DarkSurfaceElevated1,
    surfaceElevated2 = DarkSurfaceElevated2,
    progressBackground = DarkProgressBackground,
    quickButtonPressed = DarkQuickButtonPressed,
    waterGradientStart = DarkWaterGradientStart,
    waterGradientEnd = DarkWaterGradientEnd,
    successGradientStart = DarkSuccessGradientStart,
    successGradientEnd = DarkSuccessGradientEnd
)
